version: "3.7"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    # entrypoint: sh start.sh
    ports:
      - "8000:8000"
    tty: true
    volumes:
      - .:/usr/src/app:cached
    networks:
      - microservices_playground

networks:
  microservices_playground: