apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-config
data:
  DB_DRIVER_ASYNC: "postgresql+asyncpg"
  DB_DRIVER_SYNC: "postgresql"
  DB_HOST: {{ printf "%s" (include "postgresql.fullname" .) }}
  DB_PORT: "5432"
  SERVER_HOST: "0.0.0.0"
  SERVER_PORT: "80"
  SERVER_DEBUG: "False"
  SERVER_ACCESS_LOG: "False"
  SERVER_RELOAD: "False"
  SERVER_LOG_LEVEL: "info"
---
apiVersion: v1
kind: Secret
metadata:
  name: hello-secret
type: Opaque
data:
  DB_NAME: {{ printf "%s" .Values.postgresql.postgresqlDatabase | b64enc | quote }}
  DB_USER: {{ printf "%s" .Values.postgresql.postgresqlUsername | b64enc | quote }}
  DB_PASSWORD: {{ printf "%s" .Values.postgresql.postgresqlPassword | b64enc | quote }}
