{
 "title": "homework_dashboard Copy",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "by API methods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency 0.5",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \n      sum by (le, exported_endpoint) \n         (rate(app_request_latency_seconds_bucket[1m]))\n) * 1000\n",
     "legendFormat": "{{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Latency 0.95",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \n      sum by (le, exported_endpoint) \n         (rate(app_request_latency_seconds_bucket[1m]))\n) * 1000\n",
     "legendFormat": "{{ exported_endpoint }}"
    }
   ]
  },
  {
   "title": "Latency 0.99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n      sum by (le, exported_endpoint) \n         (rate(app_request_latency_seconds_bucket[1m]))\n) * 1000\n",
     "legendFormat": "{{ exported_endpoint }}"
    }
   ]
  },
  {
   "title": "Latency max",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1,\n      sum by (le, exported_endpoint) \n         (rate(app_request_latency_seconds_bucket[1m]))\n) * 1000\n",
     "legendFormat": "{{ exported_endpoint }}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_endpoint) (rate(app_request_count_total[1m])) ",
     "legendFormat": "RPS {{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (http_status, exported_endpoint) (increase(app_request_count_total{http_status=~\"5.+\"}[1m]))",
     "legendFormat": "status_code:  {{ http_status }} for: {{ exported_endpoint }}"
    }
   ]
  },
  { "title": "by the whole service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(nginx_ingress_controller_request_duration_seconds_count[1m])) ",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.+\"}[1m]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Latency 0.5",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \n      sum by (le, exported_endpoint) \n         (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))\n) * 1000\n",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Latency 0.95",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \n      sum by (le, exported_endpoint) \n         (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))\n) * 1000\n",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Latency 0.99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n      sum by (le, exported_endpoint) \n         (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))\n) * 1000\n",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Latency max",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, \n      sum by (le, exported_endpoint) \n         (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))\n) * 1000\n",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "system",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true
  }
 ]
}