apiVersion: batch/v1
kind: Job
metadata:
  name: "myapp"
spec:
  template:
    metadata:
      name: "myapp"
    spec:
      restartPolicy: Never
      containers:
        - name: post-install-job
          image: sergeivb/microservices-playground:0.2.2
          env:
            - name: DB_DRIVER_SYNC
              valueFrom:
                configMapKeyRef:
                  name: hello-config
                  key: DB_DRIVER_SYNC
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: hello-secret
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: hello-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hello-secret
                  key: DB_PASSWORD
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: hello-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: hello-config
                  key: DB_PORT
          command:
            - sh
            - "-c"
            - "alembic upgrade head"
  backoffLimit: 0
