prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}

grafana:
  enabled: true
  sidecar:
    dashboards:
      enabled: true
      label: grafana-dashboard
