replicaCount: 2

image:
  repository: sergeivb/microservices-playground

service:
  type: NodePort
  port: 8000

postgresql:
  enabled: true
  postgresqlUsername: "developer"
  postgresqlPassword: "123"
  postgresqlDatabase: "microservices_playground"
  service:
    port: "5432"

ingress:
  annotation: "/$1"
  host: "arch.homework"
  paths:
    - "/(.*)"
    - "/otusapp/sergei/(.*)"

metrics:
  serviceMonitor:
    enabled: true
