replicaCount: 2

image:
  repository: hello-py

service:
  type: NodePort
  port: 8000

postgresql:
  enabled: true
  postgresqlUsername: "developer"
  postgresqlPassword: "123"
  postgresqlDatabase: "microservices_playground"
  service:
    port: "5432"
